services:
  freestontots:
    image: registry.byjardin.co.uk/kelv/freestontots
    container_name: freestontots_local
    env_file:
      - .env.local
    restart: always
    networks:
      - nginx_proxy
      - mysql_db_network
    ports:
      - '8081:3000' # Optional, for local testing
    depends_on:
      - db
    command: >
      sh -c "
      node server.js
      "

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secureRootPassword
      MYSQL_DATABASE: freestontots_db
      MYSQL_USER: mysqlUser
      MYSQL_PASSWORD: securePassword
    networks:
      - mysql_db_network
    volumes:
      - db-data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306'

volumes:
  db-data:

networks:
  nginx_proxy:
  mysql_db_network:
